name: Build and publish to PyPI

on:
  push:
    tags:
      # Trigger on version tags like v1.0.0
      - v*

jobs:
  build-and-publish:
    name: Build and publish for ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    environment: pypi
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.10, 3.11, 3.12, 3.13, 3.14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel and source distribution
        run: uv build --wheel --sdist

      - name: Publish to PyPI
        run: uv publish
